name: pulumi-destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      PULUMI_HOME: ~/.pulumi     # ‚≠ê Forces Pulumi to use correct plugin dir

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./ppinfra
        run: npm install

      - name: Ensure Pulumi Home Exists
        run: mkdir -p ~/.pulumi/plugins

      - name: Install AWS Plugin 6.x in Pulumi Home
        run: pulumi plugin install resource aws 6.83.2

      - name: Destroy with Pulumi ESC + GitHub OIDC
        uses: pulumi/actions@v5
        with:
          command: destroy
          stack-name: ishwarya-dc/myworkshop/dev
          work-dir: ./ppinfra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_ENV: aws-oidc-env
          AWS_REGION: us-east-1
